version: 0.2

phases:
  install:
    commands:
      - echo Instalando dependencias de Docker...
  pre_build:
    commands:
      - echo Creando imagen de Docker...
      - docker build -t ejercicio3-app .
  build:
    commands:
      - echo Ejecutando el contenedor...
      - docker run -e VERSION_ID=$VERSION_ID --name mi_contenedor ejercicio3-app
      - docker cp mi_contenedor:/app/backup.log .
      - docker cp mi_contenedor:/app/resultados.json .
  post_build:
    commands:
      - echo Subiendo logs a S3...
      - aws s3 cp backup.log s3://rolando-ejercicio-bucket/logs/
      - aws s3 cp resultados.json s3://rolando-ejercicio-bucket/resultados/
artifacts:
  files:
    - backup.log
    - resultados.json